### ISSUE TITLE
✌学长回复第五次作业

### ISSUE THREAD

**Issue by YYGod0120** [7754496/redrockteam-afterclass-work#1]
- lv3的浅拷贝也实现一下
- 建议以后文件夹以及文件名称最好用英文，中文会有小小的bug
- 说一下浅拷贝和深拷贝(自己的理解)

**Comment by 7754496** [comment]
/* 纯手动实现浅拷贝 */

const obj = {
    name: "Sans",
    age: 25,
    obj:{
        name: "Sans",
        age: 25,
    },
};
const copy={};
for(const i in obj) copy[i]=obj[i];
obj.obj.name="Chara";
console.log(copy); //obj的改变同步到了
/*
{
    name: "Sans",
    age: 25,
    obj:{
        name: "Chara",
        age: 25,
    },
}
*/

在JavaScript中，对象变量不同于普通的值变量
对象变量是对原对象的引用
如果直接赋值拷贝两个变量都是引用的同一个对象，对对象的操作会同步到两个变量

如果想避免这一情况，可以新建一个对象进行浅拷贝

浅拷贝无法避免对象的某些属性值又为对象
对于对象属性可以重复递归拷贝，实现深拷贝
